package idp

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/stytchauth/stytch-go/v17/stytch/consumer/sessions"
)

// ScopeResult:
type ScopeResult struct {
	// Scope: The name of the scope.
	Scope string `json:"scope,omitempty"`
	// Description: A human-readable description of the scope, taken from the RBAC Policy.
	Description string `json:"description,omitempty"`
	// IsGrantable: Indicates whether the scope can be granted. Users can only grant scopes if they have the
	// required permissions.
	IsGrantable bool `json:"is_grantable,omitempty"`
}

// MANUAL(Types)(TYPES)
// ADDIMPORT: "github.com/stytchauth/stytch-go/v17/stytch/consumer/sessions"
// ADDIMPORT: "github.com/golang-jwt/jwt/v5"
type IntrospectTokenResponse struct {
	Active       bool             `json:"active"`
	TokenType    string           `json:"token_type"`
	Issuer       string           `json:"iss"`
	Subject      string           `json:"sub"`
	Audience     []string         `json:"aud"`
	Scope        string           `json:"scope"`
	ClientID     string           `json:"client_id"`
	Expiry       *jwt.NumericDate `json:"exp"`
	IssuedAt     *jwt.NumericDate `json:"iat"`
	CustomClaims map[string]any
}

type IntrospectTokenClaims struct {
	ClientID string `json:"client_id"`
	Scope    string `json:"scope"`
	JTI      string `json:"jti"`
	jwt.RegisteredClaims
}

type IntrospectTokenLocalParams struct {
	Token              string
	MaxTokenAge        time.Duration
	AuthorizationCheck *sessions.AuthorizationCheck
}

type IntrospectTokenNetworkParams struct {
	Token              string
	ClientID           string
	ClientSecret       *string
	TokenTypeHint      *string
	AuthorizationCheck *sessions.AuthorizationCheck
}

// ENDMANUAL(Types)
