package saml

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"github.com/stytchauth/stytch-go/v8/stytch/b2b/sso"
)

// CreateConnectionParams: Request type for `CreateConnection`.
// Fields:
//   - OrganizationID: Globally unique UUID that identifies a specific Organization. The `organization_id`
//     is critical to perform operations on an Organization, so be sure to preserve this value.
//   - DisplayName: A human-readable display name for the connection.
type CreateConnectionParams struct {
	OrganizationID string `json:"organization_id,omitempty"`
	DisplayName    string `json:"display_name,omitempty"`
}

// DeleteVerificationCertificateParams: Request type for `DeleteVerificationCertificate`.
// Fields:
//   - OrganizationID: The organization ID that the SAML connection belongs to.
//   - ConnectionID: The ID of the SAML connection.
//   - CertificateID: The ID of the certificate to be deleted.
type DeleteVerificationCertificateParams struct {
	OrganizationID string `json:"organization_id,omitempty"`
	ConnectionID   string `json:"connection_id,omitempty"`
	CertificateID  string `json:"certificate_id,omitempty"`
}

// UpdateConnectionParams: Request type for `UpdateConnection`.
// Fields:
//   - OrganizationID: Globally unique UUID that identifies a specific Organization. The `organization_id`
//     is critical to perform operations on an Organization, so be sure to preserve this value.
//   - ConnectionID: Globally unique UUID that identifies a specific SSO `connection_id` for a Member.
//   - IdpEntityID: A globally unique name for the IdP. This will be provided by the IdP.
//   - DisplayName: A human-readable display name for the connection.
//   - AttributeMapping: An object that represents the attributes used to identify a Member. This object
//     will map the IdP-defined User attributes to Stytch-specific values. Required attributes: `email` and one
//     of `full_name` or `first_name` and `last_name`.
//   - X509Certificate: A certificate that Stytch will use to verify the sign-in assertion sent by the IdP,
//     in [PEM](https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail) format. See our [X509
//     guide](https://stytch.com/docs/b2b/api/saml-certificates) for more info.
//   - IdpSsoURL: The URL for which assertions for login requests will be sent. This will be provided by
//     the IdP.
type UpdateConnectionParams struct {
	OrganizationID   string         `json:"organization_id,omitempty"`
	ConnectionID     string         `json:"connection_id,omitempty"`
	IdpEntityID      string         `json:"idp_entity_id,omitempty"`
	DisplayName      string         `json:"display_name,omitempty"`
	AttributeMapping map[string]any `json:"attribute_mapping,omitempty"`
	X509Certificate  string         `json:"x509_certificate,omitempty"`
	IdpSsoURL        string         `json:"idp_sso_url,omitempty"`
}

// CreateConnectionResponse: Response type for `CreateConnection`.
// Fields:
//   - RequestID: Globally unique UUID that is returned with every API call. This value is important to log
//     for debugging purposes; we may ask for this value to help identify a specific API call when helping you
//     debug an issue.
//   - StatusCode: The HTTP status code of the response. Stytch follows standard HTTP response status code
//     patterns, e.g. 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX
//     are server errors.
//   - Connection: The `SAML Connection` object affected by this API call. See the [SAML Connection
//     Object](https://stytch.com/docs/b2b/api/saml-connection-object) for complete response field details.
type CreateConnectionResponse struct {
	RequestID  string             `json:"request_id,omitempty"`
	StatusCode int32              `json:"status_code,omitempty"`
	Connection sso.SAMLConnection `json:"connection,omitempty"`
}

// DeleteVerificationCertificateResponse: Response type for `DeleteVerificationCertificate`.
// Fields:
//   - RequestID: Globally unique UUID that is returned with every API call. This value is important to log
//     for debugging purposes; we may ask for this value to help identify a specific API call when helping you
//     debug an issue.
//   - CertificateID: The ID of the certificate that was deleted.
//   - StatusCode: The HTTP status code of the response. Stytch follows standard HTTP response status code
//     patterns, e.g. 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX
//     are server errors.
type DeleteVerificationCertificateResponse struct {
	RequestID     string `json:"request_id,omitempty"`
	CertificateID string `json:"certificate_id,omitempty"`
	StatusCode    int32  `json:"status_code,omitempty"`
}

// UpdateConnectionResponse: Response type for `UpdateConnection`.
// Fields:
//   - RequestID: Globally unique UUID that is returned with every API call. This value is important to log
//     for debugging purposes; we may ask for this value to help identify a specific API call when helping you
//     debug an issue.
//   - StatusCode: The HTTP status code of the response. Stytch follows standard HTTP response status code
//     patterns, e.g. 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX
//     are server errors.
//   - Connection: The `SAML Connection` object affected by this API call. See the [SAML Connection
//     Object](https://stytch.com/docs/b2b/api/saml-connection-object) for complete response field details.
type UpdateConnectionResponse struct {
	RequestID  string             `json:"request_id,omitempty"`
	StatusCode int32              `json:"status_code,omitempty"`
	Connection sso.SAMLConnection `json:"connection,omitempty"`
}
