run:
  deadline: 1m
  skip-dirs:
  modules-download-mode: readonly
linters-settings:
  goimports:
    local-prefixes: github.com/stytchauth/stytch-go/stytch
  lll:
    line-length: 200
issues:
  exclude-rules:
    # Ignore comments with long urls
    - linters:
        - lll
      source: "^\\s*//\\s+https:"
    # Ignore false postitive hardcoded credentials warning in types.go
    - path: stytch/consumer/sessions/types.go
      text: "G101"
linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - gofumpt
    - gosec
    - gosimple
    - lll
    - misspell
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - unconvert
    - unused
