package sessions

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"

	"github.com/stytchauth/stytch-go/v7/stytch"
	"github.com/stytchauth/stytch-go/v7/stytch/stytcherror"
)

type Client struct {
	C *stytch.Client
}

const subURL = "sessions"

func (c *Client) Get(
	ctx context.Context,
	body *stytch.GetParams,
) (*stytch.GetResponse, error) {
	path := subURL + "//v1/sessions"

	var retVal stytch.GetResponse
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("Oops, something seems to have gone wrong marshalling the request body")
		}
	}

	err = c.C.NewRequest(ctx, "GET", path, nil, jsonBody, &retVal)

	return &retVal, err
}

func (c *Client) Authenticate(
	ctx context.Context,
	body *stytch.AuthenticateParams,
) (*stytch.AuthenticateResponse, error) {
	path := subURL + "//v1/sessions/authenticate"

	var retVal stytch.AuthenticateResponse
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("Oops, something seems to have gone wrong marshalling the request body")
		}
	}

	err = c.C.NewRequest(ctx, "POST", path, nil, jsonBody, &retVal)

	return &retVal, err
}

func (c *Client) Sessionsrevoke(
	ctx context.Context,
	body *stytch.SessionsrevokeParams,
) (*stytch.SessionsrevokeResponse, error) {
	path := subURL + "//v1/sessions/revoke"

	var retVal stytch.SessionsrevokeResponse
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("Oops, something seems to have gone wrong marshalling the request body")
		}
	}

	err = c.C.NewRequest(ctx, "POST", path, nil, jsonBody, &retVal)

	return &retVal, err
}

func (c *Client) Sessionsjwks(
	ctx context.Context,
	body *stytch.SessionsjwksParams,
) (*stytch.SessionsjwksResponse, error) {
	path := subURL + "//v1/sessions/jwks/{project_id}"

	var retVal stytch.SessionsjwksResponse
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("Oops, something seems to have gone wrong marshalling the request body")
		}
	}

	err = c.C.NewRequest(ctx, "GET", path, nil, jsonBody, &retVal)

	return &retVal, err
}
