package stytch

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type DebugServiceWhoamiParams struct{}

type DebugServiceWhoamiResponse struct {
	RequestID string `json:"request_id,omitempty"`
	ProjectID string `json:"project_id,omitempty"`
	Name      string `json:"name,omitempty"`
}
