package stytch

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type MagicLinksMagiclinkredirectParams struct {
	PublicToken     string `json:"public_token,omitempty"`
	Token           string `json:"token,omitempty"`
	StytchTokenType string `json:"stytch_token_type,omitempty"`
}
type MagicLinksMagiclinksredirectcaptchaParams struct {
	PublicToken string `json:"public_token,omitempty"`
	RedirectUrl string `json:"redirect_url,omitempty"`
	Captcha     string `json:"captcha,omitempty"`
}

type MagicLinksMagiclinkredirectResponse struct {
	RequestID        string `json:"request_id,omitempty"`
	RedirectUrl      string `json:"redirect_url,omitempty"`
	HtmlResponseData []byte `json:"html_response_data,omitempty"`
}
type MagicLinksMagiclinksredirectcaptchaResponse struct {
	RequestID   string `json:"request_id,omitempty"`
	RedirectUrl string `json:"redirect_url,omitempty"`
}
