package stytch

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type MultiTenantSessionServiceMultitenantgetParams struct {
	OrganizationID string `json:"organization_id,omitempty"`
	MemberID       string `json:"member_id,omitempty"`
}
type MultiTenantSessionServiceMultitenantauthenticateParams struct {
	SessionToken           string         `json:"session_token,omitempty"`
	SessionDurationMinutes int32          `json:"session_duration_minutes,omitempty"`
	SessionJwt             string         `json:"session_jwt,omitempty"`
	SessionCustomClaims    map[string]any `json:"session_custom_claims,omitempty"`
}
type MultiTenantSessionServiceMultitenantsessionsrevokeParams struct {
	MemberSessionID string `json:"member_session_id,omitempty"`
	SessionToken    string `json:"session_token,omitempty"`
	SessionJwt      string `json:"session_jwt,omitempty"`
	MemberID        string `json:"member_id,omitempty"`
}
type MultiTenantSessionServiceMultitenantsessionsexchangeParams struct {
	OrganizationID         string         `json:"organization_id,omitempty"`
	SessionToken           string         `json:"session_token,omitempty"`
	SessionJwt             string         `json:"session_jwt,omitempty"`
	SessionDurationMinutes int32          `json:"session_duration_minutes,omitempty"`
	SessionCustomClaims    map[string]any `json:"session_custom_claims,omitempty"`
}

type MultiTenantSessionServiceMultitenantgetResponse struct {
	RequestID      string          `json:"request_id,omitempty"`
	MemberSessions []MemberSession `json:"member_sessions,omitempty"`
}
type MultiTenantSessionServiceMultitenantauthenticateResponse struct {
	RequestID     string        `json:"request_id,omitempty"`
	MemberSession MemberSession `json:"member_session,omitempty"`
	SessionToken  string        `json:"session_token,omitempty"`
	SessionJwt    string        `json:"session_jwt,omitempty"`
	Member        Member        `json:"member,omitempty"`
	Organization  Organization  `json:"organization,omitempty"`
}
type MultiTenantSessionServiceMultitenantsessionsrevokeResponse struct {
	RequestID string `json:"request_id,omitempty"`
}
type MultiTenantSessionServiceMultitenantsessionsexchangeResponse struct {
	RequestID     string        `json:"request_id,omitempty"`
	MemberID      string        `json:"member_id,omitempty"`
	MemberSession MemberSession `json:"member_session,omitempty"`
	SessionToken  string        `json:"session_token,omitempty"`
	SessionJwt    string        `json:"session_jwt,omitempty"`
	Member        Member        `json:"member,omitempty"`
	Organization  Organization  `json:"organization,omitempty"`
}
