package stytch

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type OrganizationsOrganizationscreateParams struct {
	OrganizationName     string         `json:"organization_name,omitempty"`
	OrganizationSlug     string         `json:"organization_slug,omitempty"`
	OrganizationLogoUrl  string         `json:"organization_logo_url,omitempty"`
	TrustedMetadata      map[string]any `json:"trusted_metadata,omitempty"`
	SsoJitProvisioning   string         `json:"sso_jit_provisioning,omitempty"`
	EmailAllowedDomains  []string       `json:"email_allowed_domains,omitempty"`
	EmailJitProvisioning string         `json:"email_jit_provisioning,omitempty"`
	EmailInvites         string         `json:"email_invites,omitempty"`
	AuthMethods          string         `json:"auth_methods,omitempty"`
	AllowedAuthMethods   []string       `json:"allowed_auth_methods,omitempty"`
}
type OrganizationsOrganizationsgetParams struct {
	OrganizationID string `json:"organization_id,omitempty"`
}
type OrganizationsOrganizationsupdateParams struct {
	OrganizationID                       string         `json:"organization_id,omitempty"`
	OrganizationName                     string         `json:"organization_name,omitempty"`
	OrganizationSlug                     string         `json:"organization_slug,omitempty"`
	OrganizationLogoUrl                  string         `json:"organization_logo_url,omitempty"`
	TrustedMetadata                      map[string]any `json:"trusted_metadata,omitempty"`
	SsoDefaultConnectionID               string         `json:"sso_default_connection_id,omitempty"`
	SsoJitProvisioning                   string         `json:"sso_jit_provisioning,omitempty"`
	SsoJitProvisioningAllowedConnections []string       `json:"sso_jit_provisioning_allowed_connections,omitempty"`
	EmailAllowedDomains                  []string       `json:"email_allowed_domains,omitempty"`
	EmailJitProvisioning                 string         `json:"email_jit_provisioning,omitempty"`
	EmailInvites                         string         `json:"email_invites,omitempty"`
	AuthMethods                          string         `json:"auth_methods,omitempty"`
	AllowedAuthMethods                   []string       `json:"allowed_auth_methods,omitempty"`
}
type OrganizationsOrganizationsdeleteParams struct {
	OrganizationID string `json:"organization_id,omitempty"`
}
type OrganizationsOrganizationsmembercreateParams struct {
	OrganizationID        string         `json:"organization_id,omitempty"`
	EmailAddress          string         `json:"email_address,omitempty"`
	Name                  string         `json:"name,omitempty"`
	TrustedMetadata       map[string]any `json:"trusted_metadata,omitempty"`
	UntrustedMetadata     map[string]any `json:"untrusted_metadata,omitempty"`
	CreateMemberAsPending bool           `json:"create_member_as_pending,omitempty"`
	IsBreakglass          bool           `json:"is_breakglass,omitempty"`
}
type OrganizationsOrganizationsmemberupdateParams struct {
	OrganizationID    string         `json:"organization_id,omitempty"`
	MemberID          string         `json:"member_id,omitempty"`
	Name              string         `json:"name,omitempty"`
	TrustedMetadata   map[string]any `json:"trusted_metadata,omitempty"`
	UntrustedMetadata map[string]any `json:"untrusted_metadata,omitempty"`
	IsBreakglass      bool           `json:"is_breakglass,omitempty"`
}
type OrganizationsOrganizationsmemberdeleteParams struct {
	OrganizationID string `json:"organization_id,omitempty"`
	MemberID       string `json:"member_id,omitempty"`
}
type OrganizationsOrganizationssearchexternalParams struct {
	Cursor string              `json:"cursor,omitempty"`
	Limit  uint32              `json:"limit,omitempty"`
	Query  ExternalSearchQuery `json:"query,omitempty"`
}
type OrganizationsOrganizationsmembersearchexternalParams struct {
	Cursor          string              `json:"cursor,omitempty"`
	Limit           uint32              `json:"limit,omitempty"`
	Query           ExternalSearchQuery `json:"query,omitempty"`
	OrganizationIds []string            `json:"organization_ids,omitempty"`
}
type OrganizationsOrganizationsmemberdeletepasswordParams struct {
	OrganizationID   string `json:"organization_id,omitempty"`
	MemberPasswordID string `json:"member_password_id,omitempty"`
}
type OrganizationsOrganizationsmembergetParams struct {
	OrganizationID string `json:"organization_id,omitempty"`
	MemberID       string `json:"member_id,omitempty"`
	EmailAddress   string `json:"email_address,omitempty"`
}

type OrganizationsOrganizationscreateResponse struct {
	RequestID    string       `json:"request_id,omitempty"`
	Organization Organization `json:"organization,omitempty"`
}
type OrganizationsOrganizationsgetResponse struct {
	RequestID    string       `json:"request_id,omitempty"`
	Organization Organization `json:"organization,omitempty"`
}
type OrganizationsOrganizationsupdateResponse struct {
	RequestID    string       `json:"request_id,omitempty"`
	Organization Organization `json:"organization,omitempty"`
}
type OrganizationsOrganizationsdeleteResponse struct {
	RequestID      string `json:"request_id,omitempty"`
	OrganizationID string `json:"organization_id,omitempty"`
}
type OrganizationsOrganizationsmembercreateResponse struct {
	RequestID    string       `json:"request_id,omitempty"`
	MemberID     string       `json:"member_id,omitempty"`
	Member       Member       `json:"member,omitempty"`
	Organization Organization `json:"organization,omitempty"`
}
type OrganizationsOrganizationsmemberupdateResponse struct {
	RequestID    string       `json:"request_id,omitempty"`
	MemberID     string       `json:"member_id,omitempty"`
	Member       Member       `json:"member,omitempty"`
	Organization Organization `json:"organization,omitempty"`
}
type OrganizationsOrganizationsmemberdeleteResponse struct {
	RequestID string `json:"request_id,omitempty"`
	MemberID  string `json:"member_id,omitempty"`
}
type OrganizationsOrganizationssearchexternalResponse struct {
	RequestID       string          `json:"request_id,omitempty"`
	Organizations   []Organization  `json:"organizations,omitempty"`
	ResultsMetadata ResultsMetadata `json:"results_metadata,omitempty"`
}
type OrganizationsOrganizationsmembersearchexternalResponse struct {
	RequestID       string          `json:"request_id,omitempty"`
	Members         []Member        `json:"members,omitempty"`
	ResultsMetadata ResultsMetadata `json:"results_metadata,omitempty"`
}
type OrganizationsOrganizationsmemberdeletepasswordResponse struct {
	RequestID    string       `json:"request_id,omitempty"`
	MemberID     string       `json:"member_id,omitempty"`
	Member       Member       `json:"member,omitempty"`
	Organization Organization `json:"organization,omitempty"`
}
type OrganizationsOrganizationsmembergetResponse struct {
	RequestID    string       `json:"request_id,omitempty"`
	MemberID     string       `json:"member_id,omitempty"`
	Member       Member       `json:"member,omitempty"`
	Organization Organization `json:"organization,omitempty"`
}
