package consumer

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/mitchellh/mapstructure"
	"github.com/stytchauth/stytch-go/v9/stytch"
	"github.com/stytchauth/stytch-go/v9/stytch/consumer/cryptowallets"
	"github.com/stytchauth/stytch-go/v9/stytch/stytcherror"
)

type CryptoWalletsClient struct {
	C stytch.Client
}

func NewCryptoWalletsClient(c stytch.Client) *CryptoWalletsClient {
	return &CryptoWalletsClient{
		C: c,
	}
}

// AuthenticateStart: Initiate the authentication of a crypto wallet. After calling this endpoint, the user
// will need to sign a message containing only the returned `challenge` field.
func (c *CryptoWalletsClient) AuthenticateStart(
	ctx context.Context,
	body *cryptowallets.AuthenticateStartParams,
) (*cryptowallets.AuthenticateStartResponse, error) {
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("error marshaling request body")
		}
	}

	var retVal cryptowallets.AuthenticateStartResponse
	err = c.C.NewRequest(
		ctx,
		"POST",
		"/v1/crypto_wallets/authenticate/start",
		nil,
		jsonBody,
		&retVal,
	)
	return &retVal, err
}

// Authenticate: Complete the authentication of a crypto wallet by passing the signature.
func (c *CryptoWalletsClient) Authenticate(
	ctx context.Context,
	body *cryptowallets.AuthenticateParams,
) (*cryptowallets.AuthenticateResponse, error) {
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("error marshaling request body")
		}
	}

	var retVal cryptowallets.AuthenticateResponse
	err = c.C.NewRequest(
		ctx,
		"POST",
		"/v1/crypto_wallets/authenticate",
		nil,
		jsonBody,
		&retVal,
	)
	return &retVal, err
}

// AuthenticateWithClaims fills in the claims pointer with custom claims from the response.
// Pass in a map with the types of values you're expecting so that this function can marshal
// the claims from the response. See ExampleClient_AuthenticateWithClaims_map,
// ExampleClient_AuthenticateWithClaims_struct for examples
func (c *CryptoWalletsClient) AuthenticateWithClaims(
	ctx context.Context,
	body *cryptowallets.AuthenticateParams,
	claims any,
) (*cryptowallets.AuthenticateResponse, error) {
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("error marshaling request body")
		}
	}

	b, err := c.C.RawRequest(
		ctx,
		"POST",
		"/v1/crypto_wallets/authenticate",
		nil,
		jsonBody,
	)
	if err != nil {
		return nil, err
	}

	// First extract the Stytch data.
	var retVal cryptowallets.AuthenticateResponse
	if err := json.Unmarshal(b, &retVal); err != nil {
		return nil, fmt.Errorf("unmarshal cryptowallets.AuthenticateResponse: %w", err)
	}

	if claims == nil {
		return &retVal, nil
	}

	if m, ok := claims.(*map[string]any); ok {
		*m = retVal.Session.CustomClaims
		return &retVal, nil
	}

	// This is where we need to convert claims into a claimsMap
	decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		Result:  &claims,
		TagName: "json",
	})
	if err != nil {
		return nil, err
	}

	err = decoder.Decode(retVal.Session.CustomClaims)
	if err != nil {
		return nil, err
	}

	return &retVal, err
}
