package consumer

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"github.com/stytchauth/stytch-go/v9/stytch"
)

type M2MClient struct {
	C       stytch.Client
	Clients *M2MClientsClient
}

func NewM2MClient(c stytch.Client) *M2MClient {
	return &M2MClient{
		C:       c,
		Clients: NewM2MClientsClient(c),
	}
}
