package devicehistory

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"time"
)

// DeviceAttributeDetails:
type DeviceAttributeDetails struct {
	// IsNew: Whether this `ip_geo_country` has been seen before for this user.
	IsNew bool `json:"is_new,omitempty"`
	// FirstSeenAt: When this `ip_geo_country` was first seen for this user. Values conform to the RFC 3339
	// standard and are expressed in UTC, e.g. `2021-12-29T12:33:09Z`.
	FirstSeenAt *time.Time `json:"first_seen_at,omitempty"`
	// LastSeenAt: When this `ip_geo_country` was last seen for this user. Values conform to the RFC 3339
	// standard and are expressed in UTC, e.g. `2021-12-29T12:33:09Z`.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
}

// DeviceInfo:
type DeviceInfo struct {
	// VisitorID: The `visitor_id` (a unique identifier) of the user's device. See the
	// [Device Fingerprinting documentation](https://stytch.com/docs/fraud/guides/device-fingerprinting/fingerprints) for more details on the `visitor_id`.
	VisitorID string `json:"visitor_id,omitempty"`
	// VisitorIDDetails: Information about the `visitor_id`.
	VisitorIDDetails *DeviceAttributeDetails `json:"visitor_id_details,omitempty"`
	// IPAddress: The IP address of the user's device.
	IPAddress string `json:"ip_address,omitempty"`
	// IPAddressDetails: Information about the `ip_address`.
	IPAddressDetails *DeviceAttributeDetails `json:"ip_address_details,omitempty"`
	// IPGeoCity: The city where the IP address is located.
	IPGeoCity string `json:"ip_geo_city,omitempty"`
	// IPGeoRegion: The region where the IP address is located.
	IPGeoRegion string `json:"ip_geo_region,omitempty"`
	// IPGeoCountry: The country code where the IP address is located.
	IPGeoCountry string `json:"ip_geo_country,omitempty"`
	// IPGeoCountryDetails: Information about the `ip_geo_country`.
	IPGeoCountryDetails *DeviceAttributeDetails `json:"ip_geo_country_details,omitempty"`
}
