/*
 * stytch_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package users_pkg

import "stytch_lib/configuration_pkg"
import "stytch_lib/models_pkg"

/*
 * Interface for the USERS_IMPL
 */
type USERS interface {
    CreateUser (*models_pkg.UserCreate) (*models_pkg.UserCreateResponse, error)

    GetUserByID (string) (*models_pkg.UserGetResponse, error)

    UpdateUser (string, *models_pkg.UserUpdate) (*models_pkg.UserUpdateResponse, error)

    DeleteUser (string) (*models_pkg.UserDeleteResponse, error)
}

/*
 * Factory for the USERS interaface returning USERS_IMPL
 */
func NewUSERS(config configuration_pkg.CONFIGURATION) *USERS_IMPL {
    client := new(USERS_IMPL)
    client.config = config
    return client
}