package stytch

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type SessionsGetParams struct {
	UserID string `json:"user_id,omitempty"`
}
type SessionsAuthenticateParams struct {
	SessionToken           string         `json:"session_token,omitempty"`
	SessionDurationMinutes int32          `json:"session_duration_minutes,omitempty"`
	SessionJwt             string         `json:"session_jwt,omitempty"`
	SessionCustomClaims    map[string]any `json:"session_custom_claims,omitempty"`
}
type SessionsSessionsrevokeParams struct {
	SessionID    string `json:"session_id,omitempty"`
	SessionToken string `json:"session_token,omitempty"`
	SessionJwt   string `json:"session_jwt,omitempty"`
}
type SessionsSessionsjwksParams struct {
	ProjectID string `json:"project_id,omitempty"`
}

type SessionsGetResponse struct {
	RequestID string          `json:"request_id,omitempty"`
	Sessions  []StytchSession `json:"sessions,omitempty"`
}
type SessionsAuthenticateResponse struct {
	RequestID    string  `json:"request_id,omitempty"`
	Session      Session `json:"session,omitempty"`
	SessionToken string  `json:"session_token,omitempty"`
	SessionJwt   string  `json:"session_jwt,omitempty"`
	User         User    `json:"user,omitempty"`
}
type SessionsSessionsrevokeResponse struct {
	RequestID string `json:"request_id,omitempty"`
}
type SessionsSessionsjwksResponse struct {
	Keys      []Key  `json:"keys,omitempty"`
	RequestID string `json:"request_id,omitempty"`
}
