package stytch

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type TOTPsCreateParams struct {
	UserID            string `json:"user_id,omitempty"`
	ExpirationMinutes int32  `json:"expiration_minutes,omitempty"`
}
type TOTPsAuthenticateParams struct {
	UserID                 string         `json:"user_id,omitempty"`
	TotpCode               string         `json:"totp_code,omitempty"`
	SessionToken           string         `json:"session_token,omitempty"`
	SessionDurationMinutes int32          `json:"session_duration_minutes,omitempty"`
	SessionJwt             string         `json:"session_jwt,omitempty"`
	SessionCustomClaims    map[string]any `json:"session_custom_claims,omitempty"`
}
type TOTPsRecoverycodesParams struct {
	UserID string `json:"user_id,omitempty"`
}
type TOTPsRecoverParams struct {
	UserID                 string         `json:"user_id,omitempty"`
	RecoveryCode           string         `json:"recovery_code,omitempty"`
	SessionToken           string         `json:"session_token,omitempty"`
	SessionDurationMinutes int32          `json:"session_duration_minutes,omitempty"`
	SessionJwt             string         `json:"session_jwt,omitempty"`
	SessionCustomClaims    map[string]any `json:"session_custom_claims,omitempty"`
}

type TOTPsCreateResponse struct {
	RequestID     string   `json:"request_id,omitempty"`
	TotpID        string   `json:"totp_id,omitempty"`
	Secret        string   `json:"secret,omitempty"`
	QrCode        string   `json:"qr_code,omitempty"`
	RecoveryCodes []string `json:"recovery_codes,omitempty"`
	User          User     `json:"user,omitempty"`
	UserID        string   `json:"user_id,omitempty"`
}
type TOTPsAuthenticateResponse struct {
	RequestID    string  `json:"request_id,omitempty"`
	UserID       string  `json:"user_id,omitempty"`
	SessionToken string  `json:"session_token,omitempty"`
	Session      Session `json:"session,omitempty"`
	TotpID       string  `json:"totp_id,omitempty"`
	SessionJwt   string  `json:"session_jwt,omitempty"`
	User         User    `json:"user,omitempty"`
}
type TOTPsRecoverycodesResponse struct {
	RequestID string `json:"request_id,omitempty"`
	UserID    string `json:"user_id,omitempty"`
	Totps     []TOTP `json:"totps,omitempty"`
}
type TOTPsRecoverResponse struct {
	RequestID    string  `json:"request_id,omitempty"`
	TotpID       string  `json:"totp_id,omitempty"`
	UserID       string  `json:"user_id,omitempty"`
	SessionToken string  `json:"session_token,omitempty"`
	Session      Session `json:"session,omitempty"`
	SessionJwt   string  `json:"session_jwt,omitempty"`
	User         User    `json:"user,omitempty"`
}
