package discovery

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"github.com/stytchauth/stytch-go/v15/stytch/b2b/discovery"
)

type AuthenticateParams struct {
	EmailAddress string `json:"email_address,omitempty"`
	Password     string `json:"password,omitempty"`
}

type AuthenticateResponse struct {
	RequestID                string                             `json:"request_id,omitempty"`
	EmailAddress             string                             `json:"email_address,omitempty"`
	IntermediateSessionToken string                             `json:"intermediate_session_token,omitempty"`
	DiscoveredOrganizations  []discovery.DiscoveredOrganization `json:"discovered_organizations,omitempty"`
	StatusCode               int32                              `json:"status_code,omitempty"`
}
