package secrets

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"github.com/stytchauth/stytch-go/v16/stytch/consumer/connectedapps"
)

type RotateCancelParams struct {
	ClientID string `json:"client_id,omitempty"`
}

type RotateParams struct {
	ClientID string `json:"client_id,omitempty"`
}

type RotateStartParams struct {
	ClientID string `json:"client_id,omitempty"`
}

type RotateCancelResponse struct {
	RequestID    string                     `json:"request_id,omitempty"`
	ConnectedApp connectedapps.ConnectedApp `json:"connected_app,omitempty"`
	StatusCode   int32                      `json:"status_code,omitempty"`
}

type RotateResponse struct {
	RequestID    string                     `json:"request_id,omitempty"`
	ConnectedApp connectedapps.ConnectedApp `json:"connected_app,omitempty"`
	StatusCode   int32                      `json:"status_code,omitempty"`
}

type RotateStartResponse struct {
	RequestID    string                                         `json:"request_id,omitempty"`
	ConnectedApp connectedapps.ConnectedAppWithNextClientSecret `json:"connected_app,omitempty"`
	StatusCode   int32                                          `json:"status_code,omitempty"`
}
