package discovery_service

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"

	"github.com/stytchauth/stytch-go/v7/stytch"
	"github.com/stytchauth/stytch-go/v7/stytch/stytcherror"
)

type Client struct {
	C *stytch.Client
}

const subURL = "discovery_service"

func (c *Client) Discoveryorganizations(
	ctx context.Context,
	body *stytch.DiscoveryorganizationsParams,
) (*stytch.DiscoveryorganizationsResponse, error) {
	path := subURL + "//v1/b2b/discovery/organizations"

	var retVal stytch.DiscoveryorganizationsResponse
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("Oops, something seems to have gone wrong marshalling the request body")
		}
	}

	err = c.C.NewRequest(ctx, "POST", path, nil, jsonBody, &retVal)

	return &retVal, err
}

func (c *Client) Discoveryintermediatesessionexchange(
	ctx context.Context,
	body *stytch.DiscoveryintermediatesessionexchangeParams,
) (*stytch.DiscoveryintermediatesessionexchangeResponse, error) {
	path := subURL + "//v1/b2b/discovery/intermediate_sessions/exchange"

	var retVal stytch.DiscoveryintermediatesessionexchangeResponse
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("Oops, something seems to have gone wrong marshalling the request body")
		}
	}

	err = c.C.NewRequest(ctx, "POST", path, nil, jsonBody, &retVal)

	return &retVal, err
}

func (c *Client) Discoveryorganizationcreate(
	ctx context.Context,
	body *stytch.DiscoveryorganizationcreateParams,
) (*stytch.DiscoveryorganizationcreateResponse, error) {
	path := subURL + "//v1/b2b/discovery/organizations/create"

	var retVal stytch.DiscoveryorganizationcreateResponse
	var jsonBody []byte
	var err error
	if body != nil {
		jsonBody, err = json.Marshal(body)
		if err != nil {
			return nil, stytcherror.NewClientLibraryError("Oops, something seems to have gone wrong marshalling the request body")
		}
	}

	err = c.C.NewRequest(ctx, "POST", path, nil, jsonBody, &retVal)

	return &retVal, err
}
