package b2b

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"

	"github.com/stytchauth/stytch-go/v11/stytch"
	"github.com/stytchauth/stytch-go/v11/stytch/b2b/rbac"
)

type B2BRBACClient struct {
	C stytch.Client
}

func NewB2BRBACClient(c stytch.Client) *B2BRBACClient {
	return &B2BRBACClient{
		C: c,
	}
}

func (c *B2BRBACClient) Policy(
	ctx context.Context,
	body *rbac.PolicyParams,
) (*rbac.PolicyResponse, error) {
	var retVal rbac.PolicyResponse
	err := c.C.NewRequest(
		ctx,
		"GET",
		"/v1/b2b/rbac/policy",
		nil,
		nil,
		&retVal,
	)
	return &retVal, err
}
