package b2b

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"github.com/stytchauth/stytch-go/v13/stytch"
)

type SCIMClient struct {
	C           stytch.Client
	Connections *SCIMConnectionsClient
}

func NewSCIMClient(c stytch.Client) *SCIMClient {
	return &SCIMClient{
		C: c,

		Connections: NewSCIMConnectionsClient(c),
	}
}
